### ISSUE TITLE
Clarification on where json files go?  A sample walkthrough of setting up persistance?

### ISSUE THREAD

**Issue by famewolf** [ventoy/backend#1]
Ok I've got persistence_ext4_1GB_casper-rw.img and a bunch of iso files on the first partition of my flashdrive.  I see a bunch of files on the 2nd partition.   I can't tell if the .json file I create is supposed to be on the first or the 2nd partition.

**Comment by ventoy** [comment]
The 1st partition, with full path  **/ventoy/ventoy.json**  (need to create the ventoy directory by yourself)

**Comment by famewolf** [comment]
Thank you.  I have created the following after reading on the forum:

famewolf@hp810-135qe /media/famewolf/ventoy $ tree
.
├── ISO
│   ├── bodhi-5.0.0-64.iso
│   ├── bodhi-5.0.0-legacy.iso
│   ├── clonezilla-live-2.6.6-15-amd64.iso
│   ├── clonezilla-live-2.6.6-15-i686-pae.iso
│   ├── extix-20.2-64bit-kde-refracta-snapshot-calamares-2380mb-200127.iso
│   ├── extix-20.4-64bit-efi-lxqt-nvidia-mini-1170mb-20200404.iso
│   ├── extix-20.5-64bit-deepin-20beta-live-2500mb-200517.iso
│   ├── exton-os-64bit-efi-budgie-gnome-refracta-calamares-1310mb-200319.iso
│   ├── lfa-64bit-lxde-efi-refracta-nvidia-1670mb-200607.iso
│   ├── lxle-14.04.3-32bit.iso
│   ├── lxle_16.04.4_32.iso
│   ├── manjaro-kde-20.0.3-200606-linux56.iso
│   ├── manjaro-xfce-20.0.2-200531-linux56.iso
│   ├── systemrescuecd-amd64-6.1.4.iso
│   ├── systemrescuecd-i686-6.1.4.iso
│   ├── tails-amd64-3.7.1.iso
│   ├── tails-i386-2.9.1.iso
│   └── Ultimate_Boot_CD_5.3.8.iso
├── persistance
│   ├── CreatePersistentImg.sh
│   ├── lfa-64bit-lxde.img
│   ├── manjaro-kde-20.0.3.img
│   └── persistence_ext4_1GB_casper-rw.img
└── ventoy
    ├── ventoy.json
    └── ventoy.json~

My ventoy.json has:

{
    "persistence" : [
        {
            "image": "/ISO/manjaro-kde-20.0.3-200606-linux56.iso",
            "backend": "/persistence/manjaro-kde-20.0.3.img"
        },
        {
            "image": "/ISO/extix-20.2-64bit-kde-refracta-snapshot-calamares-2380mb-200127.iso",
            "backend": [
                "/persistence/persistence_ext4_1GB_casper-rw.img"
            ]
        },        
        {
            "image": "/lfa-64bit-lxde-efi-refracta-nvidia-1670mb-200607.iso",
            "backend": "/persistence/lfa-64bit-lxde.img"
        }
    ]
}

I tried to keep things simple.  persistance was not an option with any of these.  extix-20.2-64bit-kde-refracta-snapshot-calamares-2380mb-200127.iso froze in the middle of booting up (but ctrl alt delete worked to shutdown).   Can you point me in the right direction?

**Comment by ventoy** [comment]
ventoy.json should under ventoy directory.  That's  /ventoy/ventoy.json
What about other ISO files?

**Comment by famewolf** [comment]
The usb drive mounts as ventoy.  I have a directory in root called ventoy and in that directory is a file called ventoy.json.   If you meant something different please clarify.  I tried the 3 I was attempting to get persistance with....manjaro booted but no option for persistance was shown.  The extix-20.2-64bit-kde-refracta-snapshot-calamares-2380mb-200127.iso gives me a screen where "boot without persistance" is the only visible option.  The other two don't even do that.  They just boot as normal without persistence.   I tried bodhi which is NOT in the persistance list and it also booted as normal.  To clarify the tree..I have 3 subdirs.  All the iso's are in ISO.  All the persistance files are in persistence and ventoy.json is in ventoy.  I'm gonna double check to make sure i spelled persistence right since I see I mispelled it here a few times.

**Comment by ventoy** [comment]
OK.
In the boot menu, press  c  to enter grub shell and run    **vt_dump_persistence**

**Comment by famewolf** [comment]
I had the folder "persistence" mispelled as persistance.  I tried manjaro and it offered the option to boot with persistence.
