### ISSUE TITLE
vtoycow files isn't in image 4.0 .zip file..!!

### ISSUE THREAD

**Issue by zerocoolroot** [ventoy/backend#3]
Hi,

Sorry my bad English, I'm from Brazil.!!

The vtoycow files is not in persistence image file 4.0 (images.zip)

**persistence_ext4_256MB_vtoycow.dat.7z
persistence_ext4_512MB_vtoycow.dat.7z
persistence_ext4_1GB_vtoycow.dat.7z
persistence_ext4_2GB_vtoycow.dat.7z
persistence_ext4_4GB_vtoycow.dat.7z**

**persistence_xfs_256MB_vtoycow.dat.7z
persistence_xfs_512MB_vtoycow.dat.7z
persistence_xfs_1GB_vtoycow.dat.7z
persistence_xfs_2GB_vtoycow.dat.7z
persistence_xfs_4GB_vtoycow.dat.7z**

https://github.com/ventoy/backend/releases

Or I'm wrong..?? If yes, sorry..!!

Thanks in advance..!!

**Comment by ventoy** [comment]
5.0 updated.

**Comment by zerocoolroot** [comment]
Thank you so much..!!
