### ISSUE TITLE
Black Screen on Ventoy Persistence Plugin..!!

### ISSUE THREAD

**Issue by zerocoolroot** [ventoy/backend#4]
Hi,

Firstly, thank you so much by your amazing tool..!!

Sorry my bad english, I'm from Brazil..!!

I tryed to use Ventoy Persistence Plugin but I get the Black Screen after I choose **persistence_ext4_4GB_vtoycow.dat** or **persistence_xfs_4GB_vtoycow.dat**.

Both .dat files are **persistence** folder.

![persistence_folder](https://user-images.githubusercontent.com/44586443/114950108-c40d0480-9e28-11eb-870b-255599579d7b.png)

I did like this.

![01](https://user-images.githubusercontent.com/44586443/114950263-0f271780-9e29-11eb-9782-3f0154d1324a.png)

![02](https://user-images.githubusercontent.com/44586443/114950227-00d8fb80-9e29-11eb-92b4-efc7443ed0fd.png)

Or

![02_1](https://user-images.githubusercontent.com/44586443/114951164-e869e080-9e2a-11eb-9bb0-4c1a58d6d122.png)

![03](https://user-images.githubusercontent.com/44586443/114950234-046c8280-9e29-11eb-8773-c18ff5404713.png)

After I choose **F33 Work**, I get the Black Screen below..!!

![04](https://user-images.githubusercontent.com/44586443/114950336-2ebe4000-9e29-11eb-9ea5-efd7469e7b58.png)

My ventoy.json code..!!

{

	"theme": {
	
        "file": "/ventoy/themes/Tela/theme.txt",
		"gfxmode": "1024x768",
        "display_mode": "GUI",
        "ventoy_left": "5%",
        "ventoy_top": "95%",
        "ventoy_color": "#D2691E"
    },
	
	"menu_alias" : [
	
        {
            "image": "/ISOs/4WinKey_Ultimate_WinPE10.iso",
            "alias": "4WinKey Ultimate WinPE10"
        },		
		{
            "image": "/ISOs/Acronis_Backup_Advanced_11.7.50230_Linux.iso",
            "alias": "Acronis Backup Advanced 11.7.50230 - Linux"
        },		
		{
            "image": "/ISOs/Acronis_Backup_Advanced_11.7.50230_Windows.iso",
            "alias": "Acronis Backup Advanced 11.7.50230 - Windows"
        },
        {
            "image": "/ISOs/Acronis_True_Image_2019_Build_17750_Linux.iso",
            "alias": "Acronis True Image 2019 Build 17750 - Linux"
        },
        {
            "image": "/ISOs/Acronis_True_Image_2019_Build_17750_Windows.iso",
            "alias": "Acronis True Image 2019 Build 17750 - Windows"
        },
        {
            "image": "/ISOs/Acronis_True_Image_2020_Build_25700_Linux.iso",
            "alias": "Acronis True Image 2020 Build 25700 - Linux"
        },
        {
            "image": "/ISOs/Acronis_True_Image_2020_Build_25700_Windows.iso",
            "alias": "Acronis True Image 2020 Build 25700 - Windows"
        },
		{
            "image": "/ISOs/Acronis_True_Image_2021_Build_32010_Linux.iso",
            "alias": "Acronis True Image 2021 Build 32010 - Linux"
        },
		{
            "image": "/ISOs/Acronis_True_Image_2021_Build_32010_Windows.iso",
            "alias": "Acronis True Image 2021 Build 32010 - Windows"
        },
        {
            "image": "/ISOs/Boot_Repair_Disk_x64.iso",
            "alias": "Boot Repair Disk x64"
        },
		{
            "image": "/ISOs/DLC_Boot_2019_3.6_Final.iso",
            "alias": "DLC Boot 2019 3.6 - Final"
        },		
		{
            "image": "/ISOs/ISEE_Windows_Password_Recovery_v2.6.2.2.iso",
            "alias": "ISEE Windows Password Recovery v2.6.2.2"
        },		
		{
            "image": "/ISOs/Linux_Fedora_Cin_Live_x64_v33_15.03.2021.iso",
            "alias": "Linux Fedora Cinnamon x64 v33 - 15.03.2021"
        },
        {
            "image": "/ISOs/Linux_Fedora_Work_Live_x64_v33_15.03.2021.iso",
            "alias": "Linux Fedora Workstation x64 v33 - 15.03.2021"
        },
		{
            "image": "/ISOs/Deepin_Live_System_v2.0_amd64.iso",
            "alias": "Deepin Live System v2.0 x64"
        },
        {
            "image": "/ISOs/Linux_Mint_20_Cinnamon_x64_15.02.2021.iso",
            "alias": "Linux Mint 20 Cinnamon x64 - 15.02.2021"
        },
		{
            "image": "/ISOs/Linux_Ubuntu_20.04.2_x64.iso",
            "alias": "Linux Ubuntu 20.04.2 x64"
        },
		{
            "image": "/ISOs/Linux_Ubuntu_20.10_x64.iso",
            "alias": "Linux Ubuntu 20.10"
        },
		{
            "image": "/ISOs/openSUSE_Tumbleweed_x64.iso",
            "alias": "Linux openSUSE x64"
        },
		{
            "image": "/ISOs/Manjaro_Gnome_20.2_x64_v59.iso",
            "alias": "Linux Manjaro 20.2 x64"
        },
        {
            "image": "/ISOs/MiniTool_Partition_Wizard_11.5.iso",
            "alias": "MiniTool Partition Wizard 11.5"
        },
        {
            "image": "/ISOs/MiniTool_Partition_Wizard_12.3.iso",
            "alias": "MiniTool Partition Wizard 12.3"
        },
		{
            "image": "/ISOs/EaseUS_Partition_Master_15.5.iso",
            "alias": "EaseUS Partition Master 15.5"
        },
		{
            "image": "/ISOs/WIN7_PRO_MSDN_USB3.0_x64.iso",
            "alias": "Windows 7 Pro 30.09.2020"
        },
        {
            "image": "/ISOs/WIN8.1_PRO_MSDN_x64.iso",
            "alias": "Windows 8.1 Pro 04.10.2020"
        },
        {
            "image": "/ISOs/WIN10_PRO_19042.804_E_W8_PRO_x64.iso",
            "alias": "W10 PRO 19042.804 e W8.1 PRO"
        }		
				
		
    ],
	
	
	"menu_class" : [
        {
           "key": "4WinKey_Ultimate_WinPE10",
           "class": "4winkey"
        },
		{
           "key": "Acronis_Backup_Advanced_11.7.50230_Linux",
           "class": "acronisba"
        },
		{
           "key": "Acronis_Backup_Advanced_11.7.50230_Windows",
           "class": "acronisba"
        },
		{
           "key": "Acronis_True_Image_2019_Build_17750_Linux",
           "class": "acronisti"
        },
		{
           "key": "Acronis_True_Image_2019_Build_17750_Windows",
           "class": "acronisti"
        },
		{
           "key": "Acronis_True_Image_2020_Build_25700_Linux",
           "class": "acronisti"
        },
		{
           "key": "Acronis_True_Image_2020_Build_25700_Windows",
           "class": "acronisti"
        },
		{
           "key": "Acronis_True_Image_2021_Build_32010_Linux",
           "class": "acronisti"
        },
		{
           "key": "Acronis_True_Image_2021_Build_32010_Windows",
           "class": "acronisti"
        },
		{
           "key": "Boot_Repair_Disk_x64",
           "class": "bootrepairdisk"
        },
		{
           "key": "DLC_Boot_2019_3.6_Final",
           "class": "dlcboot"
        },
		{
           "key": "ISEE_Windows_Password_Recovery_v2.6.2.2",
           "class": "isee"
        },
		{
           "key": "Linux_Fedora_Cin_Live_x64_v33_15.03.2021",
           "class": "fedora"
        },
		{
           "key": "Linux_Fedora_Work_Live_x64_v33_15.03.2021",
           "class": "fedora"
        },
		{
           "key": "Linux_Ubuntu_20.04.2_x64",
           "class": "ubuntu"
        },
		{
           "key": "Linux_Ubuntu_20.10_x64",
           "class": "ubuntu"
        },
		{
           "key": "openSUSE_Tumbleweed_x64",
           "class": "opensuse"
        },
		{
           "key": "Manjaro_Gnome_20.2_x64_v59",
           "class": "manjaro"
        },
		{
           "key": "Deepin_Live_System_v2.0_amd64",
           "class": "deepin"
        },
		{
           "key": "Linux_Mint_20_Cinnamon_x64_15.02.2021",
           "class": "linuxmint"
        },
		{
            "key": "MiniTool_Partition_Wizard_11.5",
            "class": "minitool"
        },
		{
           "key": "MiniTool_Partition_Wizard_12.3",
           "class": "minitool"
        },
		{
           "key": "EaseUS_Partition_Master_15.5",
           "class": "easeus"
        },
		{
            "key": "WIN7_PRO_MSDN_USB3.0_x64",
            "class": "windows"
        },
		{
            "key": "WIN8.1_PRO_MSDN_x64",
            "class": "windows"
        },
		{
           "key": "WIN10_PRO_19042.804_E_W8_PRO_x64",
           "class": "windows"
        }
		
		

    ],
    
    
    "persistence": [
        {
            "image": "/ISOs/Linux_Fedora_Work_Live_x64_v33_15.03.2021.iso",
            "backend": "/persistence/persistence_xfs_4GB_vtoycow.dat"
        }
    ]
    
}

Coul'd I be doing something wrong..??

Thanks in advance..!!

**Comment by ventoy** [comment]
Does this iso file boot OK without persistence config?

**Comment by zerocoolroot** [comment]
> Does this iso file boot OK without persistence config?

Yes..!!

**Comment by zerocoolroot** [comment]
@ventoy 

If you help, follow the ISO link below.

https://drive.google.com/file/d/11TIGlGOuMXQSbwempi-fFPRsjcsPEt3w/view

**Comment by ventoy** [comment]
Does it work if you use a standard fedora release (e.g. Fedora-Workstation-Live-x86_64-33-1.2.iso) ?

**Comment by ventoy** [comment]
1. Ventoy doesn't support persistence for Fedora with an osmin.img (`/LiveOS/osmin.img`). You must remove this from the ISO file.
2. The initramfs in this ISO file doesn't contain xfs.ko, so you need to use `persistence_ext4_4GB_vtoycow.dat`

**Comment by zerocoolroot** [comment]
> 1. Ventoy doesn't support persistence for Fedora with an osmin.img (`/LiveOS/osmin.img`). You must remove this from the ISO file.
> 2. The initramfs in this ISO file doesn't contain xfs.ko, so you need to use `persistence_ext4_4GB_vtoycow.dat`

@ventoy 

I tried to use **Fedora-Workstation-Live-x86_64-33-1.2.iso** and **persistence_ext4_4GB_vtoycow.dat**, and works fine..!!

But the Fedora Updated (e.g. Linux_Fedora_Work_Live_x64_v33_15.03.2021.iso) doesn't works fine..!!

**Comment by ventoy** [comment]
Use this CI release:
https://github.com/ventoy/Ventoy/actions/runs/761962986

**Attention**
You need to add `selinux=0` option to the kernel boot option.
(press `tab`  at the `F33 Work` boot menu, add `selinux=0` at the end and press enter to boot.

**Comment by DRRDietrich** [comment]
> **Attention**
> You need to add `selinux=0` option to the kernel boot option.

Is it possible to make this change permanent?

**Comment by bassmannate** [comment]
Agreed. If this could be made permanent, that would be great. Also, I got the F33 Work menu the first time I booted with persistence and now I can't remember how I did it.

**Comment by slmn1231** [comment]
It's the same problem with me and It's not starting again I tried smos and replace ram all are not working It's just black screen only keyboard lights and fans
