### ISSUE TITLE
secure boot option does not work with some distrobutions

### ISSUE THREAD

**Issue by fafamnzm** [ventoy/backend#8]
I checked the secure boot option on the setup app and i see the lock icon on the ventoy created file.

however, after assigning a key for the secure boot for the USB, the ventoy page is shown to choose the desired distro. however, it does not work for the following distroes:

Kali, Ubunto, PopOs (all latest versions)

I also checked with Fedora 36 and it works for this distro only if the test and run option is selected. there is an option at the start of the bootup, where it can be chosen to test the media first and then run the linux. 
It does not work if the test is skipped

the error shown is : `first boot the kernel`

**Comment by ventoy** [comment]
Can these ISO files boot OK if you disable secure boot option in your BIOS?

**Comment by fafamnzm** [comment]
yes, they all work fine when i disable the secure boot, but when i enable it, and assign the key with the blue screen and `vntyefi` select thing, only fedora works.

**Comment by fafamnzm** [comment]
yes, they all work fine when i disable the secure boot, but when i enable it, and assign the key with the blue screen and vntyefi select thing, only fedora works.

also i did not mean to close the issue. i don't know why it closed it
